### ISSUE TITLE
installation on raspi or 386 (ubuntu/budgie) not working at all

### ISSUE THREAD

**Issue by gdampf** [fossasia/pslab-desktop#226]
trying to make pslab-desktop-apps running on ubuntu or raspi is a nightmare.
the installer.sh is a piece of crap.

first try on ubuntu:
Installed pslab and pslab-apps succesfully with no errors, but starting Experiments ends up in a stack-trace reg. not found modules (at least sip and apt-pkg was mentioned).
Before posting endless traces: Does anybody made the same experience?
I have several versions of python installed (2.7, 3.6 and 3.7 at least) and tried this within the 2.7-Environment as well as in 3.7, with the same result. Well, at least the 2.7 should work, as I use it also for PlatformIO, which works perfectly.
What is so special on this pslab? I don't want to create a completely isolated environment just for that.

second try:
Ohhh, what a lousy description.
I managed to get some of the dependencies solved, but when starting, I got the following errors) see below).
IMHO, I struggling with versions! I'm using python3.6 and PyQt5, so I installed pyqt5-dev-tools instead of Version 4 - does this matter?

Did anybody managed to get this running on ubuntu with python 3.6 and PyQt5?

Here, the errors (the gui is displayed, but I am unable to connect to the hardware - tried all serial lines available):

`$ Experiments
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
Traceback (most recent call last):
File "/usr/bin/Experiments", line 236, in changeSubSection
self.loadParentModuleIcons(self.subSectionPaths[ind])
File "/usr/bin/Experiments", line 247, in loadParentModuleIcons
self.loadSubmoduleIcons(submodule)
File "/usr/bin/Experiments", line 266, in loadSubmoduleIcons
icon = self.experimentIcon(submodule,app,fn)
File "/usr/lib/python3/dist-packages/PSL_Apps/utilitiesClass.py", line 1168, in init
tmp = importlib.import_module(basepackage+'.'+name)
File "/usr/lib/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 955, in _find_and_load_unlocked
File "", line 665, in _load_unlocked
File "", line 678, in exec_module
File "", line 219, in _call_with_frames_removed
File "/usr/share/pslab/psl_res/GUI/A_TEST_AND_MEASUREMENT/A_TandM/C_stream.py", line 15, in
from templates import ui_arbitStream as arbitStream
ImportError: cannot import name 'ui_arbitStream'
16384
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'`

next try on a raspi (python 3.5 and 2.7 pre-installed normal raspian):
all packages installed as described: python-pyqt5, pyqt5-dev-tools, python3-numpy, python3-scipy, python3-pyqt5.qtopengl via apt, pyqtgraph, pyopengl, qtconsole and templates via pip3):
Syntax Error (template format not supported - needs python 3.6+)

last try (self build python 3.6.8):
ModuleNotFoundError: No module named 'PSL_Apps'
I give up!

Ey, I just bought that board to experiment with hardware, not to reinvent python development!!!

Has anybody a quick cookbook, how to install this apps step by step beginning with a fresh raspian installation or a standard ubuntu/budgie ? I would really appreciate that. The description in the readme.md is not helpful at all.
Otherwise, I should better send back the device and save a lot of time......

BR
Guido

**Comment by gdampf** [comment]
btw... the make requires python, not python3. I had to use a sym link to make it run with python3 - strange - in the readme is python3 the prerequisite!!!

**Comment by gdampf** [comment]
This project is real chaos!
I found finally a way, to get pslab (not the apps) working with python 2.7 and had luck with python 3.6.7 for pslab-apps, but never with both parts using the same version. Please document the requirement exactly and test your scripts against this written document at least on some common systems (like raspi or ubuntu). Otherwise this positive project will die soon!

**Comment by gdampf** [comment]
With python 3.5 (Builtin for Raspian) and an additional pip3 install templates (details see above), I still stick on the error, that python 3.5 seems not to understand templates of the format like `self.template.add(f'<{self.name}{self._extras()}>')` as in line 84 of templates/base.py
Which version of templates did you use????

**Comment by gdampf** [comment]
If I uninstall templates, the Error is No module named 'templates' (line 15 in <module>) - maybe, the error is not the wrong version of templates, as templates seems to be a internal module.

For this day - I quit!
